# SPDX-License-Identifier: MIT-0
---
# handlers file for new role

- name: Docker down {{ ansible_role_name | basename }}  # noqa: name[casing]
  ansible.builtin.command: "{{ compose_command | default('docker compose') }} down"
  args:
    chdir: "{{ path }}"
  register: compose_down_result  # noqa: var-naming[no-role-prefix]
  changed_when: >-
    compose_down_result.stdout is search('Removing')
    or compose_down_result.stdout is search('Stopped')
  failed_when: false
  listen: docker down {{ ansible_role_name | basename }}

- name: Docker up {{ ansible_role_name | basename }}  # noqa: name[casing]
  ansible.builtin.command: >-
    {{ compose_command | default('docker compose') }} up -d
  args:
    chdir: "{{ path }}"
  register: compose_up_result  # noqa: var-naming[no-role-prefix]
  changed_when: >-
    compose_up_result.stdout is search('Creating')
    or compose_up_result.stdout is search('Recreating')
    or compose_up_result.stdout is search('Starting')
  listen: docker up {{ ansible_role_name | basename }}

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  listen: reload nginx
