---
- name: Deploy bash configs
  ansible.builtin.import_tasks: bash.yml
  tags: [dotfiles, bash]

- name: Run macOS bootstrap tasks
  ansible.builtin.import_tasks: macos-setup.yml
  tags: [bootstrap, homebrew, appstore, ssh, system]
  when: dotfiles_level == 'macbook'

- name: Deploy macOS configs
  ansible.builtin.import_tasks: macos.yml
  tags: [dotfiles, configs, macos]
  when: dotfiles_level == 'macbook'

- name: Deploy Linux configs
  ansible.builtin.import_tasks: linux.yml
  tags: [dotfiles, linux]
  when: dotfiles_level in ['homelab', 'vps']

- name: Install net-peek
  ansible.builtin.import_tasks: net-peek.yml
  tags: [dotfiles, net-peek]
  when: dotfiles_level in dotfiles_net_peek_levels
