---
- name: Include common file copy tasks
  include_tasks: "{{ playbook_dir }}/../roles/common/tasks/filescopy.yml"
  vars:
    up_handler_name: "docker up {{ role_name | basename }}"
    down_handler_name: "docker down {{ role_name | basename }}"
    files_source_dir: "{{ role_path }}/files/"