---
galaxy_info:
  author: "0x3654"
  description: Time Machine share in host samba (fruit/streams_xattr + avahi)
  company: "0x3654"
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie

  galaxy_tags:
    - samba
    - timemachine
    - backup

dependencies: []
