---
galaxy_info:
  author: 0x3654
  description: Semaphore Ansible UI role
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - docker
    - semaphore
    - ansible

dependencies: []
