---
# defaults file for homelab

# Required system packages
required_packages:  # noqa: var-naming[no-role-prefix]
  - docker-ce
  - docker-compose-plugin

# Docker repository installation control
install_docker_repo: true  # noqa: var-naming[no-role-prefix]
update_repo: true  # noqa: var-naming[no-role-prefix]
force_repo_update: false  # noqa: var-naming[no-role-prefix]

# User and paths
folder_user: "{{ ansible_role_name | basename }}"  # noqa: var-naming[no-role-prefix]
homelab_samba_user: "{{ ansible_role_name | basename }}"
pwd: "/server"  # noqa: var-naming[no-role-prefix]
path: "{{ pwd }}/{{ ansible_role_name | basename }}"  # noqa: var-naming[no-role-prefix]

# File permissions
directory_mode: "0755"  # noqa: var-naming[no-role-prefix]
file_mode: "0644"  # noqa: var-naming[no-role-prefix]

# tautulli
homelab_tautulliport: "8181"
# tailscale proxy
homelab_tsdproxy_enable: true


# transmisiion
homelab_transmission_port: "9091"
homelab_transmission_download_dir: "/mnt/torrent/movie"
homelab_transmission_incomplete_dir: "/tmp"
homelab_transmission_watch_dir: "/mnt/torrent/new"
# transmisiion-rss
homelab_trans_rss_download_path: "/mnt/torrent/tv show"
homelab_trans_rss_update_interval: "600"
# torrserver
homelab_torrserverport: "8090"
