# SPDX-License-Identifier: MIT-0
---
# handlers file for vpn_servers

- name: Restart docker amneziawg
  ansible.builtin.shell: "{{ common_compose_command | default('docker compose') }} restart amnezia-wg-easy"
  args:
    chdir: "{{ path }}"
  register: vpnserver_compose_result
  changed_when: >-
    (vpnserver_compose_result.stdout ~ vpnserver_compose_result.stderr) is search('Restarting')
  when:
    - ansible_facts['architecture'] != 'aarch64'
    - vpnserver_amneziawg_enabled | default(true)

- name: Restart docker fail2ban
  ansible.builtin.shell: "{{ common_compose_command | default('docker compose') }} restart fail2ban"
  args:
    chdir: "{{ path }}"
  register: vpnserver_compose_result
  changed_when: >-
    (vpnserver_compose_result.stdout ~ vpnserver_compose_result.stderr) is search('Restarting')

- name: Docker down vpnserver
  ansible.builtin.command: "{{ common_compose_command | default('docker compose') }} down"
  args:
    chdir: "{{ path }}"
  register: vpnserver_compose_down_result
  changed_when: >-
    vpnserver_compose_down_result.stdout is search('Removing')
    or vpnserver_compose_down_result.stdout is search('Stopped')
  failed_when: false
  listen: docker down vpnserver

- name: Docker up vpnserver
  ansible.builtin.command: "{{ common_compose_command | default('docker compose') }} up -d"
  args:
    chdir: "{{ path }}"
  register: vpnserver_compose_up_result
  changed_when: >-
    vpnserver_compose_up_result.stdout is search('Creating')
    or vpnserver_compose_up_result.stdout is search('Recreating')
    or vpnserver_compose_up_result.stdout is search('Starting')
  listen: docker up vpnserver

- name: Stop docker 3x-ui
  community.docker.docker_container:
    name: 3x-ui
    state: stopped

- name: Start docker 3x-ui
  community.docker.docker_container:
    name: 3x-ui
    state: started
