---
galaxy_info:
  author: "0x3654"
  description: Mediaserver stack files on micro (plex + tautulli + frp tunnel, /git/docker/mediaserver)
  company: "0x3654"
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - bookworm

  galaxy_tags:
    - plex
    - tautulli
    - frp

dependencies: []
