---
base_firewall_rules:
  - "-A INPUT -p tcp -m tcp --dport {{ ssh_port | default(22) }} -j ACCEPT"
  - "-A INPUT -p tcp -m tcp --dport {{ http_port | default(80) }} -j ACCEPT"
  - "-A INPUT -p tcp -m tcp --dport {{ https_port | default(443) }} -j ACCEPT"
  - "-A INPUT -i lo -j ACCEPT"
  - "-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT"