---
- name: Удаление базы данных 3x-ui
  hosts: vpn_servers_role
  gather_facts: false
  become: true
  vars:
    sub_path: /server/3x-ui-sub
  
  tasks:
    - name: Cleanup 3x-ui
      block:
        - name: Stop 3x-ui container
          shell: docker stop sub_proxy || true
          args:
            executable: /bin/bash
          ignore_errors: true

        - name: Remove 3x-ui container
          shell: docker rm 3x-ui || true
          args:
            executable: /bin/bash
          ignore_errors: true

        - name: Remove 3x-ui directory
          file:
            path: "{{ sub_path }}"
            state: absent
      tags: [cleanup 3x-ui]