---
- name: Удаление базы данных 3x-ui
  hosts: vpn_servers_role
  gather_facts: false
  become: true
  #vars:
  #ui_db_path: /server/3x-ui/db
  #ui_path: /server/3x-ui/
  
  tasks:
    - name: Include default variables
      include_vars:
        file: ../roles/vpn_servers/defaults/main.yml
    - name: Cleanup 3x-ui
      block:
        - name: Stop 3x-ui container
          shell: docker stop 3x-ui || true
          args:
            executable: /bin/bash
          ignore_errors: true

        - name: Remove 3x-ui container
          shell: docker rm 3x-ui || true
          args:
            executable: /bin/bash
          ignore_errors: true

        - name: Remove 3x-ui directory
          file:
            path: "{{ xray_path }}"
            state: absent
            
      tags: [cleanup-3x-ui]