---
# GISP Downloader - Download CSV files from minpromtorg.gov.ru
- name: GISP Downloader
  hosts: gisp_role
  gather_facts: false
  tasks:
    - name: Run downloader container
      community.docker.docker_compose_v2:
        project_src: "{{ gisp_project_src }}"
        services:
          - downloader
        run: rm
        state: present
      register: downloader_result

    - name: Show downloader results
      ansible.builtin.debug:
        var: downloader_result
